import React from 'react'
import { NavBar } from "./NavBar"
const Contact: React.FC = () => {
  return (
    <>


      <h2>Contact  page</h2>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sollicitudin urna ligula, non efficitur urna bibendum volutpat. Quisque tincidunt lorem eros, ac condimentum ipsum condimentum non. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis fringilla ultrices quam. Fusce metus ante, venenatis eu turpis ut, commodo mattis metus. Pellentesque sit amet sem vel dolor congue accumsan eget et massa. Quisque rhoncus magna nibh, in bibendum dolor imperdiet vitae. Praesent dapibus efficitur est, in aliquam felis finibus eu. Phasellus nec purus sit amet velit ultrices maximus. Proin tristique iaculis ex, a ullamcorper risus pellentesque non. Ut euismod in mi vitae sodales. In id augue id nisl tincidunt congue ut vel risus. Donec ligula ligula, lacinia non maximus eget, finibus vel ipsum. Nullam consequat porttitor eros, ac bibendum massa hendrerit eu.

        Maecenas et ultricies eros. Nunc sed odio sit amet lorem dignissim pharetra ac a nunc. Aenean ut rutrum metus. Donec posuere elementum dolor eu posuere. Praesent pretium arcu non felis facilisis, tincidunt suscipit ipsum efficitur. Suspendisse facilisis congue mi nec cursus. Nulla facilisi. Quisque quis laoreet massa.

        Nullam nisl libero, luctus et ornare vel, euismod ut eros. Donec ac tellus iaculis, molestie tellus vel, suscipit lacus. Nam nec tristique tortor, sit amet iaculis mauris. Aliquam nec ex at eros fermentum ullamcorper consectetur in ligula. Quisque in massa dolor. Sed ac sapien venenatis, euismod turpis nec, euismod lectus. Sed luctus porttitor leo vel volutpat. Aenean ullamcorper gravida leo, id finibus odio posuere sed. Aenean tincidunt lobortis ante vel mollis. Nullam non neque nec est condimentum tempus ut at tellus. Nulla maximus nunc et ipsum consequat laoreet. Nam euismod leo orci. Proin eros tellus, ornare vel diam a, pharetra suscipit tellus. Sed vitae sagittis diam. Phasellus in bibendum augue, sed fringilla erat.

        Pellentesque id sapien nunc. Suspendisse eleifend turpis arcu, vitae fermentum lorem hendrerit at. Pellentesque cursus tempor bibendum. Curabitur faucibus ornare felis, non rhoncus ex maximus sit amet. Aenean varius sapien vulputate, tincidunt augue eget, semper risus. Nulla mattis purus sed dignissim placerat. Nullam leo elit, maximus at ante in, dapibus rhoncus velit. Phasellus velit diam, pulvinar in sollicitudin vitae, dignissim id tortor. Praesent efficitur ac risus ut euismod. Vivamus ac pretium justo, non efficitur lectus. Nunc molestie orci at nisi dignissim tempor. Duis gravida consequat eros eu vulputate. Integer urna purus, consequat vitae molestie vel, mollis eget odio.

        Etiam rhoncus, sem eu vulputate blandit, turpis orci pulvinar est, eget condimentum enim tortor ut metus. Cras dui mauris, porta at est ac, auctor tincidunt urna. In vel aliquam lacus, ac venenatis urna. Mauris luctus maximus orci, id pretium ligula maximus et. Nunc commodo nibh quis varius sollicitudin. Maecenas velit lectus, vulputate quis ultrices ut, finibus sed nisi. Sed sit amet venenatis massa.

        Donec id ipsum et lectus iaculis viverra eget ac ex. Suspendisse accumsan at lorem finibus rhoncus. Quisque condimentum faucibus ex nec imperdiet. Proin molestie, risus et ullamcorper euismod, est libero porttitor risus, vestibulum suscipit quam metus id justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum venenatis hendrerit nunc eu eleifend. Donec consectetur facilisis magna non porttitor. Curabitur congue tortor quis dolor imperdiet, quis interdum nunc pellentesque. Duis vel sagittis tellus. Maecenas mollis cursus efficitur. Nulla facilisi.

        Integer ut est sit amet augue porta aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque ac urna a felis sodales volutpat. Curabitur dignissim, eros ac interdum mattis, purus dui fringilla elit, sed iaculis justo risus id justo. Duis efficitur lobortis nibh ac egestas. Nam tempor metus vel elit ultrices, quis eleifend nisi rutrum. Sed dapibus iaculis aliquam. Mauris tincidunt ullamcorper urna, nec viverra ligula varius eu. Curabitur vitae mi placerat, pellentesque tellus eu, ultrices nunc. Quisque aliquam luctus risus nec rutrum.

        Mauris in pulvinar nunc. Aenean malesuada vehicula molestie. Nam hendrerit accumsan rhoncus. Donec justo tellus, condimentum eu nisl non, imperdiet semper velit. Praesent rutrum ornare velit et fringilla. Integer porttitor odio non purus dignissim, quis vulputate lectus fermentum. Fusce vehicula euismod felis vitae sollicitudin. Ut a massa et purus lobortis tincidunt in sed urna. Cras quis diam at augue scelerisque gravida. Proin nec molestie elit. In sed nisi felis. Suspendisse tristique neque ac ipsum mollis congue. Duis accumsan in neque at pretium.

        Nam euismod pulvinar vulputate. Proin et neque a arcu mollis pharetra vel sit amet diam. Donec quis sagittis quam. Suspendisse nec leo turpis. Nam massa turpis, gravida non urna id, ullamcorper semper diam. Cras eget sapien sit amet sapien euismod egestas id sit amet odio. Nulla semper pulvinar sagittis.

        Donec ornare erat vitae arcu scelerisque vestibulum. Mauris convallis pharetra augue, vitae porta eros porttitor vel. Etiam dictum malesuada nunc ac tincidunt. Sed sed lectus ullamcorper, egestas turpis non, vehicula tortor. Vivamus dui orci, porta nec venenatis a, semper eu nunc. Pellentesque tristique augue in pellentesque eleifend. Integer in porttitor mauris. Fusce varius arcu vel augue elementum, non volutpat turpis semper. Vestibulum egestas nulla eu augue molestie facilisis. Curabitur et orci lorem. Maecenas pharetra hendrerit mattis.

        Vestibulum fringilla, nisi facilisis ornare condimentum, libero nulla ullamcorper mauris, commodo ornare urna mauris a massa. Quisque ut diam blandit, posuere neque ac, consequat sem. Aliquam pretium turpis et ligula laoreet euismod ac id velit. Quisque a rhoncus justo. In id turpis sed magna malesuada euismod quis sit amet lacus. Aenean a arcu orci. Ut ornare, risus in sodales sagittis, sem ipsum blandit ex, non condimentum augue arcu a elit. Suspendisse lacinia ornare quam eu pharetra. Morbi sed efficitur est.

        Nunc non odio id tortor gravida accumsan et lobortis purus. Donec et aliquet massa, non mollis elit. Aliquam in tincidunt mi, eu lobortis mi. Quisque porta volutpat justo, sed pellentesque tellus sollicitudin eu. Praesent tempus pharetra orci a posuere. Mauris sapien velit, dapibus non viverra vel, ornare nec tortor. Praesent id tempor urna, accumsan tempor nunc. Nullam consectetur semper finibus. Integer imperdiet est eros, ut tempus diam sollicitudin at. Sed ornare, lacus convallis vestibulum congue, ligula dui ornare turpis, quis mattis lectus massa aliquam felis. Etiam et est in mauris aliquam molestie.

        Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Cras condimentum nisi in lectus imperdiet, ac semper leo tempor. Maecenas quis est dictum nulla fermentum mattis. Morbi lacinia tortor in lorem faucibus volutpat. Mauris interdum, est sed pretium blandit, elit arcu faucibus sem, in aliquet diam nunc non erat. Integer a ultrices ante. Proin nulla leo, malesuada sed odio quis, facilisis tincidunt leo. Suspendisse commodo quis libero non imperdiet. Fusce sed condimentum odio. Maecenas pulvinar nibh pulvinar, fermentum risus eget, eleifend justo. Aenean eleifend dignissim condimentum.

        Donec semper metus non semper consequat. Nam tempus nulla ac tellus mollis fermentum. Aenean interdum dignissim malesuada. Mauris sed felis tristique, tincidunt nibh sed, rutrum augue. Duis vitae libero vitae ipsum vulputate auctor. Integer aliquam luctus nisl, non egestas diam ultricies quis. Curabitur in purus sodales, hendrerit quam sed, consectetur neque. Nullam turpis dui, fringilla in metus sed, sollicitudin fringilla odio. Ut vitae massa laoreet, imperdiet felis aliquam, tincidunt nisi. Nulla consectetur tincidunt leo, maximus imperdiet mi posuere at. Sed tempor arcu vel vestibulum efficitur. Pellentesque vel est mi. Curabitur a erat dignissim, malesuada nulla ac, faucibus nulla.

        Nullam eu leo in arcu gravida fringilla. Nunc lorem risus, faucibus ac turpis sed, tempus consequat tellus. Aenean velit magna, tempor et pretium sit amet, gravida at leo. In volutpat justo non odio luctus, eu sodales nibh varius. Morbi venenatis purus finibus ante consectetur ultrices. Sed eget venenatis urna. Nulla in nulla ac tellus ultricies tristique. Maecenas a est tortor. Duis auctor cursus posuere. Nam vestibulum turpis sed massa mollis, et mollis nisi porttitor. Vivamus eleifend dolor augue, id commodo nunc faucibus vitae.

        Nullam facilisis nunc vel velit consectetur, quis dignissim risus finibus. Maecenas non nibh quis lacus congue eleifend vel id nulla. Proin porttitor sapien vitae mi faucibus, eu rhoncus tellus convallis. Sed luctus erat ac neque molestie imperdiet. Integer porta nisi non massa pretium, vel porta justo tempus. Ut scelerisque urna tempor diam consectetur, a vulputate mi porttitor. Proin pharetra, nisi non elementum lacinia, est nisi ultrices mauris, non rhoncus justo mauris ac tellus. Morbi id lorem ac lacus auctor cursus ut non quam. Mauris ac nulla magna. In in ullamcorper nisi. Sed bibendum tempus efficitur. Duis commodo tortor nec nunc tristique vestibulum.

        Aenean eu turpis at lectus ornare fringilla ac sit amet tellus. Nunc eu pulvinar turpis. Phasellus eget risus pulvinar, ullamcorper ipsum quis, porttitor mauris. Nam ante dolor, volutpat vitae pulvinar quis, ultrices vel nunc. Cras nisi leo, venenatis non suscipit in, fringilla eu orci. Integer sed urna lacinia, viverra diam sed, ullamcorper diam. Curabitur ac lacus convallis, ullamcorper lorem quis, hendrerit quam. Suspendisse ut scelerisque lacus, vel bibendum sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eget magna lorem. Vivamus fringilla ultricies elit quis iaculis. Mauris id justo quis libero venenatis blandit. Curabitur nec felis accumsan, interdum lectus quis, lacinia erat. In a rhoncus dolor. Vivamus mi justo, consequat ut fringilla vitae, pellentesque rutrum ex.

        Aenean consequat risus velit, at interdum ligula laoreet eget. Suspendisse potenti. Donec dui augue, lacinia vel ultrices sed, elementum quis turpis. Proin feugiat et augue sit amet vulputate. Nullam viverra metus libero, non ullamcorper neque molestie vitae. Maecenas a sodales nulla. Donec convallis mi porta, aliquam sapien quis, viverra justo. Praesent consequat lorem eleifend sollicitudin ultricies. Ut vel enim et neque maximus sagittis non vel metus. Integer et diam odio. Phasellus sed dui at lectus molestie suscipit. Vivamus eget cursus sem. Suspendisse vel efficitur sapien. Donec mi dui, posuere sed pulvinar eget, imperdiet nec justo. Aliquam et placerat leo.

        Quisque auctor euismod neque ut blandit. Aliquam at laoreet dolor, vel cursus ligula. Cras orci nulla, posuere in nunc non, fermentum pellentesque mauris. Duis id maximus magna. Aenean interdum sollicitudin massa dictum maximus. Vivamus turpis erat, cursus ac sem ac, pulvinar volutpat eros. Aliquam erat volutpat. Etiam quis sollicitudin neque, sed pulvinar augue. Quisque pellentesque lobortis ante eu consequat. Aliquam quis scelerisque sem, non ultrices metus. Vestibulum egestas lorem maximus, malesuada ante ut, sodales urna. Morbi euismod turpis in nunc scelerisque, quis condimentum orci sodales. Donec ac ipsum nec ipsum lobortis egestas. Nam libero lorem, tristique vel commodo non, convallis quis felis. Vivamus leo risus, luctus ut sapien at, tincidunt laoreet magna. Vivamus sit amet egestas ante.

        Maecenas ultricies, purus ac sollicitudin tempus, sapien mauris pellentesque urna, quis venenatis nisi enim ut mi. Fusce semper, est nec imperdiet venenatis, arcu quam lobortis elit, non finibus lacus turpis vitae augue. Praesent scelerisque mi interdum diam auctor volutpat vel condimentum quam. Nullam nec magna a erat porta fermentum vitae vulputate justo. Suspendisse ut interdum justo, ut dictum dolor. Donec gravida mattis mi vitae tempus. Integer suscipit fermentum leo, id bibendum libero luctus non. Fusce nec massa in nisi facilisis tempor. Nullam ullamcorper volutpat risus a fermentum. Nulla vel dolor quis augue euismod elementum ut ut ante. In hac habitasse platea dictumst. Nunc gravida condimentum elementum. Nam eleifend varius maximus. Nulla dictum scelerisque elit, sed scelerisque augue pharetra et. Donec luctus iaculis accumsan. Nulla posuere dapibus leo.

        Vivamus id semper erat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas justo neque, varius facilisis egestas in, maximus eu tellus. Sed sed ullamcorper libero. Curabitur efficitur iaculis neque id iaculis. In hac habitasse platea dictumst. Nulla tristique mi neque, non bibendum purus laoreet quis. Mauris volutpat felis lacus, sed tincidunt quam auctor venenatis. Aliquam dui turpis, cursus vitae libero vel, eleifend varius nibh. Sed nisi lacus, malesuada sit amet turpis eget, ultricies pharetra risus.

        Quisque sit amet libero est. Vivamus enim arcu, sollicitudin in sapien id, sodales ornare neque. Ut auctor nisl non elit imperdiet mattis. Fusce non volutpat nisl, eget pellentesque leo. Vestibulum maximus ante ut massa accumsan, sed cursus tortor facilisis. Duis varius nulla eu lacus ornare, maximus auctor lectus pulvinar. Quisque consectetur imperdiet sem ac interdum. Donec justo nisl, elementum id rutrum vel, fermentum quis felis. Donec scelerisque viverra odio, vitae ultrices ante bibendum ac.

        Vivamus quis lorem vel libero dictum volutpat. Suspendisse condimentum felis eget nibh vulputate accumsan. Morbi quis odio id nisi ultricies pretium. Nam aliquet sollicitudin sem. Suspendisse ultrices maximus orci vel tempus. Mauris a diam a purus vulputate fermentum non eget enim. Mauris sed ipsum blandit, interdum neque non, egestas massa. Aenean id malesuada turpis. Nulla quis aliquam nunc. Sed lacinia, leo sed elementum bibendum, urna arcu ultrices erat, et facilisis libero ligula in libero.

        Curabitur tincidunt efficitur est, pulvinar semper mi bibendum at. Sed vitae est ullamcorper, rutrum elit et, sodales mauris. Donec nec faucibus ligula. Nam efficitur ultricies sapien non pharetra. Ut sed eros in orci scelerisque pretium eu ut quam. In nec justo eu diam blandit faucibus. Fusce vestibulum venenatis eros, non egestas libero consequat venenatis. Pellentesque auctor, turpis eu finibus rhoncus, velit nulla lacinia orci, sit amet volutpat ligula diam et leo. Proin euismod, arcu eu suscipit pellentesque, tellus odio tempus leo, vitae finibus odio eros eget ex. Morbi id ex lacus. Suspendisse nec tortor non tortor efficitur tincidunt. Ut tincidunt commodo vestibulum. Fusce aliquet eros leo, eu lobortis neque bibendum a. Suspendisse eu mi urna. Proin eu luctus ex, at elementum libero. Aliquam pellentesque, sapien ut sodales gravida, purus neque convallis neque, vel fringilla diam ante vitae felis.

        Fusce odio risus, euismod vitae mollis eu, porttitor in mauris. Cras lectus odio, accumsan sodales nulla ac, tempus vehicula nibh. In hac habitasse platea dictumst. Duis sodales mauris non efficitur mattis. Maecenas ullamcorper vulputate leo, sollicitudin interdum leo. Duis id mauris massa. Aenean tincidunt in sem vitae tristique. Ut quis tincidunt ex, nec euismod ante. Cras sapien tellus, dictum eu massa nec, gravida luctus est.

        Generated 25 paragraphs, 2269 words, 15383 bytes of Lorem Ipsum
        help@lipsum.com
      </div>
    </>
  )
}

export default Contact